### ISSUE TITLE
"Can't set multipath flags in IOCTL_COMPAT mode." error

### ISSUE THREAD

**Issue by jerome-arzel** [multipath-tcp/iproute-mptcp#4]
In v0.91, when I start `ip link set dev eth0 multipath off` there always the error `Can't set multipath flags in IOCTL_COMPAT mode.`.

In v0.90, there no such error.

**Comment by cpaasch** [comment]
I have a fix ready - will submit it soon.

**Comment by cpaasch** [comment]
FYI:

https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2016-08/msg00065.html
https://sympa-2.sipr.ucl.ac.be/sympa/arc/mptcp-dev/2016-08/msg00064.html

**Comment by cpaasch** [comment]
Fixed in https://github.com/multipath-tcp/iproute-mptcp/commit/1bd41b1a5a47b9852eca879c2b8034ca1ec29381
