### ISSUE TITLE
Wrong/old iproute-mptcp included in apt-repository

### ISSUE THREAD

**Issue by bozakov** [multipath-tcp/iproute-mptcp#6]
According to the [documentation](https://multipath-tcp.org/pmwiki.php/Users/Tools) the MPTCP apt repo should provide a modified version of iproute, which allows to disable an interface for MPTCP by doing e.g.:

    ip link set dev eth0 multipath off

However the included version (1:3.16.201711022122-jessie) doesn't seem to have the multipath extensions and returns

    Error: either "dev" is duplicate, or "multipath" is a garbage.

Compiling manually from [git](https://github.com/multipath-tcp/iproute-mptcp) works as expected.

**Comment by cpaasch** [comment]
Sorry for the late reply - are you sure that you correctly installed the package? What do you see if you type "which ip" ?

I just double-checked the binary and it is correct as far as I can see.

**Comment by bozakov** [comment]
Hi and also sorry for the late reply. Just got around to checking again on a fresh installation. The issue was that ubuntu 16.04 provides a newer package version (and i was looking at the iproute rather than iproute2 package). In case someone runs into a similar issue try this:

    which ip    # get location of ip command (/sbin/ip)
    dpkg -S /sbin/ip    # find which package provides command
    apt-cache madison iproute2    # find available package versions
    sudo apt-get install iproute2=3.16.201711022122-jessie    # downgrade to the MPTCP provided version
